### ISSUE TITLE
socket 기능 테스트

### ISSUE THREAD

**Issue by ddubbu-dev** [ddubbu-dev/Jungle-Express#17]
## TODO

- [x] 실험에 필요한 레포 찾기 완료
- [ ] 코드 이해하기
- [ ] multi user random 하게 움직이도록 수정
- [ ] 속도 개선 (UDT 수정도 고려하기)
- [ ] maximum test
- [ ] 3D 오브젝트로 바꿔보기

**Comment by ddubbu-dev** [comment]
- [x] 실험에 필요한 레포 찾기 완료
- [ ] 코드 이해하기
- [ ] multi user random 하게 움직이도록 수정
- [ ] multi user 접속 환경 그냥 브라우저 N 개 띄울까?? maximum은..?

**Comment by ddubbu-dev** [comment]
server emit > client on
* gameStateUpdate

server on

**Comment by ddubbu-dev** [comment]
server emit > client on
* gameStateUpdate

**Comment by ddubbu-dev** [comment]
## TCP vs UDP

* TCP 기반 : `socket.io`, 단점-latency (지연 시간)
* UDP 기반: `dgram`, 단점-전송 순서 보장안됨. 패킷 유실돼서 보완 로직 필요

**Comment by ddubbu-dev** [comment]
시도해볼 것
- [ ] ws 로 교체하기
- [ ] 방향키 움직임에 따라 즉각 반응 (데이터는 서버가 관리)
- [ ] 3d object로 바꿔보기

**Comment by ddubbu-dev** [comment]
개선: 방향키 반대되면 바로 움직이도록

**Comment by ddubbu-dev** [comment]
Network
- 소켓 연결이 다수가 되고, 그리고 latency 테스트


***
주제 정해지고 다음을 논할 수 있음
- 게임 로직 연산, 클라/서버 담당
- 게임 state 정의
